expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-core-tls
      notarySecretName: harbor-notar-tls

  ingress:
    hosts:
      core: harbor.peopledata.org.cn
      notary: notary.peopledata.org.cn

    controller: default
    className: "nginx"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  clusterIP:
    name: harbor
    ports:
      # The service port Harbor listens on when serving HTTP
      httpPort: 80
      # The service port Harbor listens on when serving HTTPS
      httpsPort: 443
      # The service port Notary listens on. Only needed when notary.enabled
      # is set to true
      notaryPort: 4443

externalURL: https://harbor.peopledata.org.cn

# For storing images and charts, you can also use "azure", "gcs", "s3",
# "swift" or "oss". Set it in the "imageChartStorage" section
persistence:
  enabled: true
  # Setting it to "keep" to avoid removing PVCs during a helm delete
  # operation. Leaving it empty will delete PVCs after the chart deleted
  # (this does not apply for PVCs that are created for internal database
  # and redis components, i.e. they are never deleted automatically)
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "cfsauto"
    chartmuseum:
      storageClass: "cfsauto"
    jobservice:
      jobLog:
        storageClass: "cfsauto"
    database:
      storageClass: "cfsauto"
    redis:
      storageClass: "cfsauto"
    trivy:
      storageClass: "cfsauto"

  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      region: ap-nanjing
      bucket: harbor-1304979731
      accesskey: AKIDPceW7SVHwPacNyJQTKvHOFp9F5g8KFtG
      secretkey: FI4cy8YjhSu89vRhrnSqwmMfi5D6iDrQ
      regionendpoint: cos.ap-nanjing.myqcloud.com
      secure: true

imagePullPolicy: IfNotPresent

harborAdminPassword: "HarborDiD12345"

metrics:
  enabled: true
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001

cache:
  # default is not enabled.
  enabled: true
  # default keep cache for one day.
  expireHours: 24
